# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: LEGEND
email: info@legend-exp.org
description: > # this means to ignore newlines until "baseurl:"
  #Very short description / mission statement (edit in _config.yml). 
  #Will appear in document head meta (for Google search results)
  #and in feed.xml site description.
  The mission of LEGEND is to field a Ge-76 experiment with neutrinoless double-beta
  decay discovery sensitivity well beyond 10^27 years in half-life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://legend-exp.org" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  legend-exp

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
